client:
  timeout: "1"
  beat_interval: "1"
  namespace_id: "1"
  app_name: "1"
  endpoint: "1"
  region_id: "1"
  access_key: "1"
  secret_key: "1"
  open_KMS: "1"
  cache_dir: "1"
  update_thread_num: "1"
  not_load_cache_at_start: "1"
  update_cache_when_empty: "1"
  username: "1"
  password: "1"
  log_dir: "1"
  log_level: "1"
  context_path: "1"
  log_sampling_config:
    initial: "1"
    thereafter: "1"
    tick: "1"
  log_rolling_config:
    max_size: "1"
    max_age: "1"
    max_backups: "1"
    local_time: "1"
    compress: "1"
server:
  - scheme: "1"
    context_path: "1"
    ip_addr: "1"
    port: "1"
